import React from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const A = {
  logo: 'https://shakariki432.com/wp-content/uploads/2023/03/cropped-messageImage_1678688833115-1-180x180.jpg',
  hero: 'https://shakariki432.com/wp-content/uploads/2023/06/shakariki432-shakariki432-DSC00791.jpg',
  graphic: 'https://shakariki432.com/wp-content/uploads/2023/05/22783866.png',
  parking: 'https://shakariki432.com/wp-content/uploads/2023/06/Parking-Ekamai.jpg',
  plan: 'https://shakariki432.com/wp-content/uploads/2023/07/%E8%A6%8B%E5%8F%96%E3%82%8A%E5%9B%B3-ALL-BRANCH-2023.7_page-0009-768x1024.jpg',
  official: 'https://shakariki432.com/en/brand-en/shakariki-outlet-en/shakariki-432-ekami-en/',
  line: 'https://lin.ee/Lonkelj',
  map: 'https://goo.gl/maps/SPxXHL6GLig84UA66',
  aroimaru: 'https://aroimaru.com/restaurants/shakariki432-ekkamai/',
  course: 'http://shakariki432.com/wp-content/uploads/2025/11/COURSE-MENU1.pdf',
  food: 'http://shakariki432.com/wp-content/uploads/2025/11/EKAMAI-54page-12-10-25.pdf',
  lunch: 'http://shakariki432.com/wp-content/uploads/2026/01/EKKAMAIEMSPHERE-MEGA-bangnaTHE-UP-LUNCH-2026.pdf',
  drink: 'http://shakariki432.com/wp-content/uploads/2026/04/Shakariki-Ekkamai-Drink-Menu.pdf',
  cafe: 'http://shakariki432.com/wp-content/uploads/2025/12/Cafe-Menu.pdf',
};

const menuLinks = [
  ['Course Menu', A.course, 'COURSE-MENU1.pdf'],
  ['Food Menu', A.food, 'EKAMAI 54page'],
  ['Lunch Menu', A.lunch, 'EKKAMAI / EMSPHERE / MEGA Bangna / THE UP LUNCH'],
  ['Drink Menu', A.drink, 'Shakariki Ekkamai Drink Menu'],
  ['Cafe Menu', A.cafe, 'Cafe Menu'],
];

const infoRows = [
  ['Phone Number', '02-004-1713'],
  ['日本人直通', '080-081-4342'],
  ['Address', '114/1–2, Soi Sukhumvit 63 (Ekkamai), Khlong Tan Nuea Subdistrict, Watthana District, Bangkok 10110, Thailand'],
  ['MAP', 'Google Maps'],
  ['Access', '10min from BTS Ekkamai station by Taxi.'],
  ['Business Hours', 'Everyday · 11:00 ~ 08:00'],
  ['Lunch Time', '–'],
  ['Karaoke Room', '6P×4Rooms · 12P×2Rooms · 10P×1Room · 30P×1Room'],
  ['Private Room', '2~6P × 3 Rooms · 10~12P × 2 Rooms · 12~15P × 1 Room · 16~20P × 1 Room'],
  ['Smoking Seat', 'Available'],
  ['Floor Layout', 'Available'],
  ['Car Park', 'Available'],
  ['WiFi', 'Available'],
  ['Credit Card', 'Mastercard, VISA'],
];

const outlets = ['Shakariki432 SENAFEST Charoen Nakhon','Shakariki432 City Link Korat','Shakariki432 Lat phrao Wang Hin','Shakariki432 Phrakanong','Shakariki432 Emsphere','FC Shakariki432 ARI','MALAYSIA SHAKARIKI 432 SAKE DINING','Shakariki 432 Major Ratchayothin','Shakariki432 The Paseo Park Kanchanaphisek','Shakariki432 Think Park Chiang Mai Nimmanhaemin','NEO Shakariki432 thonglor','SHAKARIKI432 Ram Intra','SHAKARIKI432 THE NINE CENTER Rama9','Shakariki 432 The Circle Ratchapruek','Shakariki 432 The Street Ratchada','SHAKARIKI 432 Eve space Bang Khae','Shakariki432 Mega Bangna','Shakariki432 Onnut Century The Movie Plaza Sukhumvit','Shakariki 432 The Up Rama 3','SHAKARIKI 432 PATTAYA','Shakariki432 Thaniya','Shakariki432 Nihonmachi','Shakariki 432 ASOKE'];

function Shell({children}) { return <div className="site-bg min-h-screen text-[#1f1a17]">{children}</div>; }
function SectionTitle({eyebrow,title,children}) { return <div className="mx-auto mb-8 max-w-5xl text-center md:mb-12"><p className="text-xs font-black uppercase tracking-[.26em] text-[#e30613]">{eyebrow}</p><h2 className="jp-stamp mt-3 text-balance text-4xl font-black leading-[.95] tracking-[-.045em] text-[#1f1a17] md:text-6xl">{title}</h2>{children && <p className="mx-auto mt-4 max-w-3xl text-base leading-7 text-[#5a4a3b] md:text-lg">{children}</p>}</div> }

function Nav(){return <header className="frost fixed left-3 right-3 top-3 z-50 mx-auto max-w-7xl rounded-[28px] px-3 py-3 md:left-6 md:right-6 md:top-5"><div className="flex items-center justify-between gap-3"><a href="#top" className="flex min-w-0 items-center gap-3"><img src={A.logo} alt="SHAKARIKI432 logo" className="h-12 w-12 rounded-full border border-black/10 bg-white object-cover"/><span className="min-w-0"><strong className="block truncate text-sm tracking-[.12em] md:text-base">SHAKARIKI432</strong><small className="block text-xs font-bold text-[#e30613]">Ekkamai</small></span></a><nav className="hidden items-center gap-6 text-sm font-black text-[#473b32] lg:flex"><a href="#menus">MENU</a><a href="#rooms">ROOMS</a><a href="#info">INFO</a><a href="#outlets">OUTLETS</a></nav><a href="tel:020041713" className="rounded-full bg-[#e30613] px-5 py-3 text-sm font-black text-white shadow-lg shadow-red-700/20">CALL</a></div></header>}

function Hero(){return <section id="top" className="mx-auto grid max-w-7xl grid-cols-1 items-center gap-8 px-4 pb-16 pt-28 md:px-8 md:pt-36 lg:grid-cols-[.9fr_1.1fr]"><div className="reveal"><div className="mb-5 inline-flex items-center gap-3 rounded-full bg-white px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-[#e30613] shadow-sm"><span className="h-2 w-2 rounded-full bg-[#e30613]"></span>Shakariki432 Ekkamai</div><h1 className="jp-stamp text-balance text-5xl font-black leading-[.88] tracking-[-.055em] text-[#1f1a17] md:text-7xl lg:text-8xl">Shakariki432 Ekkamai</h1><p className="mt-6 max-w-2xl text-xl font-semibold leading-8 text-[#43362d]">You can have banquets up to 100 people ! We have free parking and karaoke too!</p><p className="mt-3 max-w-2xl text-base leading-7 text-[#665649]">We also have concept karaoke rooms which have various themes and concepts. You can enjoy it in a group of minimum 10 up to 22 people!</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a className="rounded-full bg-[#e30613] px-7 py-4 text-center font-black text-white shadow-xl shadow-red-700/20" href="tel:020041713">Phone Number 02-004-1713</a><a className="rounded-full bg-[#1f1a17] px-7 py-4 text-center font-black text-white" href={A.line} target="_blank" rel="noopener">LINE Official Account</a><a className="rounded-full border border-[#e30613]/25 bg-white px-7 py-4 text-center font-black text-[#e30613]" href={A.map} target="_blank" rel="noopener">MAP</a></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{['Everyday','11:00 ~ 08:00','Free Parking','Karaoke'].map(x=><div key={x} className="paper-card rounded-2xl p-4 text-center text-sm font-black text-[#332820]">{x}</div>)}</div></div><div className="reveal delay-1 grid gap-4"><div className="paper-card overflow-hidden rounded-[32px] p-3"><img src={A.hero} alt="SHAKARIKI432 Ekkamai" className="h-[360px] w-full rounded-[24px] object-cover md:h-[540px]"/></div><div className="grid grid-cols-2 gap-4"><img src={A.graphic} alt="SHAKARIKI432 graphic" className="paper-card h-40 w-full rounded-[24px] object-contain p-4"/><img src={A.parking} alt="Parking Ekkamai" className="paper-card h-40 w-full rounded-[24px] object-cover p-2"/></div></div></section>}

function Menus(){return <section id="menus" className="mx-auto max-w-7xl px-4 py-16 md:px-8"><SectionTitle eyebrow="MENU" title="Official menu links from the original page">※Please note that food and drink menus may vary by location. ※The lunch menu at ASOKE, FC RAMA9 and FC RATCHAYOTHIN branch is different from other branches. ※THANIYA and FC RAM INTRA branch does not have the lunch menu.</SectionTitle><div className="grid gap-4 md:grid-cols-5">{menuLinks.map(([label,href,meta])=><a key={label} href={href} target="_blank" rel="noopener" className="paper-card rounded-[26px] p-5 transition hover:-translate-y-1 hover:border-[#e30613]/30"><span className="jp-stamp text-5xl font-black text-[#e30613]">食</span><h3 className="mt-6 text-xl font-black">{label}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[#6c5a4b]">{meta}</p><span className="mt-5 inline-flex text-sm font-black text-[#e30613]">Open PDF →</span></a>)}</div><div className="mt-5 paper-card rounded-[24px] p-5"><strong className="text-[#e30613]">Coupon</strong><span className="ml-3 text-[#5a4a3b]">Coming soon</span><a href={A.aroimaru} target="_blank" rel="noopener" className="ml-0 mt-3 inline-flex font-black text-[#1f1a17] sm:ml-5 sm:mt-0">Aroimaru(มีคูปอง) →</a></div></section>}

function Rooms(){const cards=[['Banquets','Up to 100 people'],['Karaoke Room','6P×4Rooms · 12P×2Rooms · 10P×1Room · 30P×1Room'],['Private Room','2~6P×3 · 10~12P×2 · 12~15P×1 · 16~20P×1'],['Concept Karaoke Rooms','Various themes and concepts. Minimum 10 up to 22 people.']]; return <section id="rooms" className="mx-auto max-w-7xl px-4 py-16 md:px-8"><SectionTitle eyebrow="KARAOKE ROOM / PRIVATE ROOM" title="Rooms and banquets exactly from the old site"/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{cards.map((c,i)=><article key={c[0]} className={`${i===0?'red-card':'paper-card'} rounded-[28px] p-6`}><span className="jp-stamp text-5xl font-black opacity-80">{String(i+1).padStart(2,'0')}</span><h3 className="mt-7 text-2xl font-black">{c[0]}</h3><p className={`mt-3 leading-7 ${i===0?'text-white/85':'text-[#5a4a3b]'}`}>{c[1]}</p></article>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[.82fr_1.18fr]"><div className="paper-card rounded-[28px] p-4"><img src={A.plan} alt="Floor Layout" className="max-h-[620px] w-full rounded-[20px] object-contain"/><p className="mt-3 text-center text-sm font-black text-[#e30613]">Floor Layout</p></div><div className="ink-card rounded-[28px] p-7"><h3 className="jp-stamp text-4xl font-black">Restaurant facilities</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{['Smoking Seat · Available','Car Park · Available','WiFi · Available','Credit Card · Mastercard, VISA'].map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/10 p-4 font-bold text-white/90">{x}</div>)}</div></div></div></section>}

function Info(){return <section id="info" className="mx-auto max-w-7xl px-4 py-16 md:px-8"><SectionTitle eyebrow="RESTAURANT INFORMATION" title="All original restaurant information in one clear table"/><div className="paper-card overflow-hidden rounded-[30px]"><div className="grid bg-[#e30613] px-5 py-4 text-sm font-black uppercase tracking-[.18em] text-white md:grid-cols-[240px_1fr]"><span>Field</span><span>Details</span></div>{infoRows.map(([k,v])=><div key={k} className="grid gap-2 border-b border-black/10 px-5 py-4 last:border-b-0 md:grid-cols-[240px_1fr]"><strong className="text-[#e30613]">{k}</strong><span className="leading-7 text-[#3f332b]">{v}</span></div>)}</div></section>}

function Outlets(){return <section id="outlets" className="mx-auto max-w-7xl px-4 py-16 pb-28 md:px-8"><SectionTitle eyebrow="OTHER OUTLETS" title="Other outlets from the original page"/><div className="paper-card rounded-[30px] p-5"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{outlets.map(x=><div key={x} className="rounded-2xl bg-[#f5f2ec] px-4 py-3 text-sm font-bold text-[#4a3b31]">{x}</div>)}</div></div></section>}

function Access(){return <section id="access" className="mx-auto grid max-w-7xl grid-cols-1 gap-5 px-4 py-16 md:px-8 lg:grid-cols-[1fr_1fr]"><div className="paper-card rounded-[30px] p-5"><img src={A.parking} alt="Car Park" className="h-[420px] w-full rounded-[22px] object-cover"/></div><div className="paper-card rounded-[30px] p-7"><p className="text-xs font-black uppercase tracking-[.24em] text-[#e30613]">ACCESS</p><h2 className="jp-stamp mt-3 text-4xl font-black leading-[.95] md:text-6xl">10min from BTS Ekkamai station by Taxi.</h2><p className="mt-5 leading-8 text-[#5a4a3b]">114/1–2, Soi Sukhumvit 63 (Ekkamai), Khlong Tan Nuea Subdistrict, Watthana District, Bangkok 10110, Thailand</p><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a className="rounded-full bg-[#e30613] px-6 py-4 text-center font-black text-white" href="tel:020041713">02-004-1713</a><a className="rounded-full bg-[#1f1a17] px-6 py-4 text-center font-black text-white" href="tel:0800814342">日本人直通</a><a className="rounded-full border border-black/10 bg-white px-6 py-4 text-center font-black text-[#1f1a17]" href={A.map} target="_blank" rel="noopener">MAP</a></div></div></section>}

function Demo(){return <Shell><Nav/><main><Hero/><Menus/><Rooms/><Info/><Access/><Outlets/></main><footer className="border-t border-black/10 bg-white/70 px-5 py-8 text-sm leading-7 text-[#6a5748] md:px-10"><p><strong className="text-[#1f1a17]">Concept redesign demo prepared for discussion.</strong> This is not the official website unless approved by the business owner. Restaurant facts, contacts, menu links and imagery are from public SHAKARIKI432 pages for proposal context.</p><p className="mt-2">ตัวอย่างคอนเซ็ปต์เว็บไซต์สำหรับพูดคุย/เสนอแนวทางเท่านั้น ยังไม่ใช่เว็บไซต์ทางการของธุรกิจนี้ เว้นแต่เจ้าของธุรกิจจะอนุมัติ</p></footer><div className="fixed bottom-3 left-3 right-3 z-50 grid grid-cols-3 gap-2 rounded-full border border-black/10 bg-white/90 p-2 shadow-2xl backdrop-blur-xl md:hidden"><a className="rounded-full bg-[#e30613] py-3 text-center font-black text-white" href="tel:020041713">CALL</a><a className="rounded-full bg-[#1f1a17] py-3 text-center font-black text-white" href={A.line} target="_blank" rel="noopener">LINE</a><a className="rounded-full bg-[#f5f2ec] py-3 text-center font-black text-[#1f1a17]" href={A.map} target="_blank" rel="noopener">MAP</a></div></Shell>}
function Landing(){return <Shell><main className="mx-auto max-w-5xl px-5 py-28"><p className="text-xs font-black uppercase tracking-[.28em] text-[#e30613]">TPL Design · WebClone</p><h1 className="jp-stamp mt-5 text-6xl font-black leading-[.85] tracking-[-.06em] md:text-8xl">Website redesign demos.</h1><a className="mt-10 inline-flex rounded-full bg-[#e30613] px-7 py-4 font-black text-white" href="/subproject/shakariki432-ekkamai">Open SHAKARIKI432 Ekkamai →</a></main></Shell>}
function App(){const isDemo=location.pathname.startsWith('/subproject/shakariki432-ekkamai'); document.title=isDemo?'SHAKARIKI432 Ekkamai — Original Tone Redesign Demo':'TPL Design — WebClone Demos'; return isDemo?<Demo/>:<Landing/>}
createRoot(document.getElementById('root')).render(<App/>);
